# Multi-stage build for Next.js with Node.js
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ARG NEXT_PUBLIC_MICROSOFT_CLARITY_ID
ARG NEXT_PUBLIC_GOOGLE_ADSENSE_ID
ARG NEXT_PUBLIC_AD_SOCIAL_BAR
ARG NEXT_PUBLIC_AD_NATIVE_BANNER
ARG NEXT_PUBLIC_AD_BANNER_728X90
ARG NEXT_PUBLIC_AD_BANNER_300X250
ARG NEXT_PUBLIC_AD_BANNER_468X60
ARG NEXT_PUBLIC_AD_SIDEBAR_160X600
ARG NEXT_PUBLIC_AD_SIDEBAR_160X300
ARG NEXT_PUBLIC_AD_MOBILE_320X50

FROM node:20-alpine AS deps
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json* ./
RUN npm install --legacy-peer-deps

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ARG NEXT_PUBLIC_MICROSOFT_CLARITY_ID
ARG NEXT_PUBLIC_GOOGLE_ADSENSE_ID
ARG NEXT_PUBLIC_AD_SOCIAL_BAR
ARG NEXT_PUBLIC_AD_NATIVE_BANNER
ARG NEXT_PUBLIC_AD_BANNER_728X90
ARG NEXT_PUBLIC_AD_BANNER_300X250
ARG NEXT_PUBLIC_AD_BANNER_468X60
ARG NEXT_PUBLIC_AD_SIDEBAR_160X600
ARG NEXT_PUBLIC_AD_SIDEBAR_160X300
ARG NEXT_PUBLIC_AD_MOBILE_320X50

ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
ENV NEXT_PUBLIC_MICROSOFT_CLARITY_ID=${NEXT_PUBLIC_MICROSOFT_CLARITY_ID}
ENV NEXT_PUBLIC_GOOGLE_ADSENSE_ID=${NEXT_PUBLIC_GOOGLE_ADSENSE_ID}
ENV NEXT_PUBLIC_AD_SOCIAL_BAR=${NEXT_PUBLIC_AD_SOCIAL_BAR}
ENV NEXT_PUBLIC_AD_NATIVE_BANNER=${NEXT_PUBLIC_AD_NATIVE_BANNER}
ENV NEXT_PUBLIC_AD_BANNER_728X90=${NEXT_PUBLIC_AD_BANNER_728X90}
ENV NEXT_PUBLIC_AD_BANNER_300X250=${NEXT_PUBLIC_AD_BANNER_300X250}
ENV NEXT_PUBLIC_AD_BANNER_468X60=${NEXT_PUBLIC_AD_BANNER_468X60}
ENV NEXT_PUBLIC_AD_SIDEBAR_160X600=${NEXT_PUBLIC_AD_SIDEBAR_160X600}
ENV NEXT_PUBLIC_AD_SIDEBAR_160X300=${NEXT_PUBLIC_AD_SIDEBAR_160X300}
ENV NEXT_PUBLIC_AD_MOBILE_320X50=${NEXT_PUBLIC_AD_MOBILE_320X50}

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
